export interface ClaimSearchCriteria {
  ClaimNo: string;
  CustomerOrderNo: string;
  CustomerOrderFromDate: string;
  CustomerOrderToDate: string;
  ClaimStatus: string[]; // Array of statuses
  ClaimDate: string;
  Type: string;
  CounterParty: string;
  NoteType: string;
  NoteNo: string;
  NoteDate: string;
  RefDocType: string;
  RefDocNo: string;
  ClaimCategory: string;
  WBSNo: string;
  BusinessPartnerID: string;
  BusinessPartnerName: string;
  ClaimLocationID: string;
  ClaimLocationName: string;
  ContractID: string;
  ContractDescription: string;
  AssignedUser: string;
  ClaimantRefNo: string;
  AdjustmentInvoiceNo: string;
  IncidentDateFrom: string;
  IncidentDateTo: string;
  Investigation: string;
  ClaimDateFrom: string;
  ClaimDateTo: string;
  SupplierNoteNumber: string;
  DraftBill: string;
  IncidentLocation: string;
  IncidentType: string;
  ClaimInitiatedBy: string;
  CommentRemark: string;
  Remark1: string;
  Remark2: string;
  Remark3: string;
  QC1: string;
  QCValue1: string;
  QC2: string;
  QCValue2: string;
  QC3: string;
  QCValue3: string;
  ActionResolution: string;
  SecondaryRefNo: string;
  InitiatedBy: string;
  ForwardIsFinancialAction: string;
  ExpectedDocument: string;
}

export const DEFAULT_CLAIM_SEARCH_CRITERIA: ClaimSearchCriteria = {
  ClaimNo: "",
  CustomerOrderNo: "",
  CustomerOrderFromDate: "",
  CustomerOrderToDate: "",
  ClaimStatus: [],
  ClaimDate: "",
  Type: "",
  CounterParty: "",
  NoteType: "",
  NoteNo: "",
  NoteDate: "",
  RefDocType: "",
  RefDocNo: "",
  ClaimCategory: "",
  WBSNo: "",
  BusinessPartnerID: "",
  BusinessPartnerName: "",
  ClaimLocationID: "",
  ClaimLocationName: "",
  ContractID: "",
  ContractDescription: "",
  AssignedUser: "",
  ClaimantRefNo: "",
  AdjustmentInvoiceNo: "",
  IncidentDateFrom: "",
  IncidentDateTo: "",
  Investigation: "",
  ClaimDateFrom: "",
  ClaimDateTo: "",
  SupplierNoteNumber: "",
  DraftBill: "",
  IncidentLocation: "",
  IncidentType: "",
  ClaimInitiatedBy: "",
  CommentRemark: "",
  Remark1: "",
  Remark2: "",
  Remark3: "",
  QC1: "",
  QCValue1: "",
  QC2: "",
  QCValue2: "",
  QC3: "",
  QCValue3: "",
  ActionResolution: "",
  SecondaryRefNo: "",
  InitiatedBy: "",
  ForwardIsFinancialAction: "",
  ExpectedDocument: "",
};
