// Define the type (if you're using TS)
export interface SearchCriteria {
  TripId: string;
  CustomerID: string;
  CustomerOrderNumber: string;
  ServiceType: string;
  SubServiceType: string;
  PlannedExecutionDateFrom: string;
  PlannedExecutionDateTo: string;
  TripStatus: string;
  TrainID: string;
  CustomerRefNo: string;
  RoundTrip: string;
  TripType: string;
  CustomerDescription: string;
  Departurepoint: string;
  ArrivalPoint: string;
  Supplier: string;
  SupplierContract: string;
  CustomerContract: string;
  PathNo: string;
  IncidentStatus: string;
  TransportMode: string;
  ReturnTripID: string;
  CancellationReason: string;
  WorkshopStatus: string;
  VendorFeedback: string;
  VendorFeedbackReason: string;
  WagonGroup: string;
  ContainerGroup: string;
  Via: string;
  CustomerSenderRefNo: string;
  DocumentType: string;
  VehicleID: string;
  DriverID: string;
  CarrierID: string;
  VehicleRegNo: string;
  EquipmentRegNo: string;
  VoyageFlightTrainNo: string;
  VesselFlightTrainName: string;
  THUSerialNo: string;
  RefDocType: string;
  ToLocation: string;
  Cluster: string;
  WBS: string;
  Contract: string;
  WagonID: string;
  AgentID: string;
  ScheduleID: string;
  UserID: string;
  ExecutiveCarrierID: string;
  PassNo: string;
  ContainerID: string;
  TripBillingStatus: string;
  Document: string;
  BRSenderRefNo: string;
  IncidentID: string;
  MobileRefIncidentID: string;
  RefDocNo: string;
  LoadType: string;
  LegFrom: string;
  LegTo: string;
  ScreenName: string;
}

// Default object (all empty strings)
export const defaultSearchCriteria: SearchCriteria = {
  TripId: "",
  CustomerID: "",
  CustomerOrderNumber: "",
  ServiceType: "",
  SubServiceType: "",
  PlannedExecutionDateFrom: "",
  PlannedExecutionDateTo: "",
  TripStatus: "",
  TrainID: "",
  CustomerRefNo: "",
  RoundTrip: "",
  TripType: "",
  CustomerDescription: "",
  Departurepoint: "",
  ArrivalPoint: "",
  Supplier: "",
  SupplierContract: "",
  CustomerContract: "",
  PathNo: "",
  IncidentStatus: "",
  TransportMode: "",
  ReturnTripID: "",
  CancellationReason: "",
  WorkshopStatus: "",
  VendorFeedback: "",
  VendorFeedbackReason: "",
  WagonGroup: "",
  ContainerGroup: "",
  Via: "",
  CustomerSenderRefNo: "",
  DocumentType: "",
  VehicleID: "",
  DriverID: "",
  CarrierID: "",
  VehicleRegNo: "",
  EquipmentRegNo: "",
  VoyageFlightTrainNo: "",
  VesselFlightTrainName: "",
  THUSerialNo: "",
  RefDocType: "",
  ToLocation: "",
  Cluster: "",
  WBS: "",
  Contract: "",
  WagonID: "",
  AgentID: "",
  ScheduleID: "",
  UserID: "",
  ExecutiveCarrierID: "",
  PassNo: "",
  ContainerID: "",
  TripBillingStatus: "",
  Document: "",
  BRSenderRefNo: "",
  IncidentID: "",
  MobileRefIncidentID: "",
  RefDocNo: "",
  LoadType: "",
  LegFrom: "",
  LegTo: "",
  ScreenName: 'TripExecution'
};
